// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/helloexample.proto

package helloexample

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Helloexample service

func NewHelloexampleEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Helloexample service

type HelloexampleService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Helloexample_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Helloexample_PingPongService, error)
}

type helloexampleService struct {
	c    client.Client
	name string
}

func NewHelloexampleService(name string, c client.Client) HelloexampleService {
	return &helloexampleService{
		c:    c,
		name: name,
	}
}

func (c *helloexampleService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Helloexample.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloexampleService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Helloexample_StreamService, error) {
	req := c.c.NewRequest(c.name, "Helloexample.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &helloexampleServiceStream{stream}, nil
}

type Helloexample_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type helloexampleServiceStream struct {
	stream client.Stream
}

func (x *helloexampleServiceStream) Close() error {
	return x.stream.Close()
}

func (x *helloexampleServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloexampleServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloexampleServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloexampleServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloexampleService) PingPong(ctx context.Context, opts ...client.CallOption) (Helloexample_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Helloexample.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &helloexampleServicePingPong{stream}, nil
}

type Helloexample_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type helloexampleServicePingPong struct {
	stream client.Stream
}

func (x *helloexampleServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *helloexampleServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *helloexampleServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloexampleServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloexampleServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *helloexampleServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Helloexample service

type HelloexampleHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Helloexample_StreamStream) error
	PingPong(context.Context, Helloexample_PingPongStream) error
}

func RegisterHelloexampleHandler(s server.Server, hdlr HelloexampleHandler, opts ...server.HandlerOption) error {
	type helloexample interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Helloexample struct {
		helloexample
	}
	h := &helloexampleHandler{hdlr}
	return s.Handle(s.NewHandler(&Helloexample{h}, opts...))
}

type helloexampleHandler struct {
	HelloexampleHandler
}

func (h *helloexampleHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.HelloexampleHandler.Call(ctx, in, out)
}

func (h *helloexampleHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.HelloexampleHandler.Stream(ctx, m, &helloexampleStreamStream{stream})
}

type Helloexample_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type helloexampleStreamStream struct {
	stream server.Stream
}

func (x *helloexampleStreamStream) Close() error {
	return x.stream.Close()
}

func (x *helloexampleStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloexampleStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloexampleStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloexampleStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *helloexampleHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.HelloexampleHandler.PingPong(ctx, &helloexamplePingPongStream{stream})
}

type Helloexample_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type helloexamplePingPongStream struct {
	stream server.Stream
}

func (x *helloexamplePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *helloexamplePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloexamplePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloexamplePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloexamplePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *helloexamplePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
