// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/hellomicro.proto

package hellomicro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Hellomicro service

func NewHellomicroEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Hellomicro service

type HellomicroService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Hellomicro_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Hellomicro_PingPongService, error)
}

type hellomicroService struct {
	c    client.Client
	name string
}

func NewHellomicroService(name string, c client.Client) HellomicroService {
	return &hellomicroService{
		c:    c,
		name: name,
	}
}

func (c *hellomicroService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Hellomicro.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hellomicroService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Hellomicro_StreamService, error) {
	req := c.c.NewRequest(c.name, "Hellomicro.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &hellomicroServiceStream{stream}, nil
}

type Hellomicro_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type hellomicroServiceStream struct {
	stream client.Stream
}

func (x *hellomicroServiceStream) Close() error {
	return x.stream.Close()
}

func (x *hellomicroServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hellomicroServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellomicroServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellomicroServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hellomicroService) PingPong(ctx context.Context, opts ...client.CallOption) (Hellomicro_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Hellomicro.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &hellomicroServicePingPong{stream}, nil
}

type Hellomicro_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type hellomicroServicePingPong struct {
	stream client.Stream
}

func (x *hellomicroServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *hellomicroServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *hellomicroServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellomicroServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellomicroServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *hellomicroServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Hellomicro service

type HellomicroHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Hellomicro_StreamStream) error
	PingPong(context.Context, Hellomicro_PingPongStream) error
}

func RegisterHellomicroHandler(s server.Server, hdlr HellomicroHandler, opts ...server.HandlerOption) error {
	type hellomicro interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Hellomicro struct {
		hellomicro
	}
	h := &hellomicroHandler{hdlr}
	return s.Handle(s.NewHandler(&Hellomicro{h}, opts...))
}

type hellomicroHandler struct {
	HellomicroHandler
}

func (h *hellomicroHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.HellomicroHandler.Call(ctx, in, out)
}

func (h *hellomicroHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.HellomicroHandler.Stream(ctx, m, &hellomicroStreamStream{stream})
}

type Hellomicro_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type hellomicroStreamStream struct {
	stream server.Stream
}

func (x *hellomicroStreamStream) Close() error {
	return x.stream.Close()
}

func (x *hellomicroStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hellomicroStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellomicroStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellomicroStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *hellomicroHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.HellomicroHandler.PingPong(ctx, &hellomicroPingPongStream{stream})
}

type Hellomicro_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type hellomicroPingPongStream struct {
	stream server.Stream
}

func (x *hellomicroPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *hellomicroPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hellomicroPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellomicroPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellomicroPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *hellomicroPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
